### ISSUE TITLE
Socks5 auth with Firefox?

### ISSUE THREAD

**Issue by ghost** [clue/psocksd#10]
Is there any way to let Firefox auth against a psocksd socks5-proxy?
Firefox dont ask me for credentials and the server logs:

```
error: SOCKS5 protocol error - No acceptable authentication mechanism found
```

**Comment by frm1001xplrr** [comment]
Socks5 proxy with authentication is now possible with the Proxy Toggle addon for Firefox 57+

https://addons.mozilla.org/en-US/firefox/addon/proxy-toggle/

Easy config: Server, port, username, password - done!
Easy use: Toolbar button on/off
