### ISSUE TITLE
Multiple outgoing interfaces with smart selection based on latency to destination network

### ISSUE THREAD

**Issue by ethaniel** [clue/psocksd#18]
I have this weird idea that I want to try.

I am a traveler, right now I am in Bali now, Thailand before.
In both of those asian countries I've noticed the same problem - the ISPs route most of the connections to Europe through USA which slows down the speed alot.

To get a proper connection with Europe I sometimes use a VPN service (in Singapore for example, where they have better routing). But that on the other hand slows down my connections with USA.

So, I came up with this idea that I think is only doable with your PHP daemon.

When a new connection is being established, send out pings to the destination host through all available network interfaces (that will be the primary connection + the VPN connection). And once the replies are back, establish the outgoing socket through the faster interface. It adds a little overhead to every new connection, but the resulting speeds can be faster.

Example: So, for example, when I ping "vk.com" through a primary connection, I get 400ms (because it goes through USA) and 288ms through VPN (because it goes through europe). So, I would prefect to talk to "vk.com" through my VPN interface.

But, "youtube.com" would be faster through my primary connection, because they have geo distribution, the ping on the primary connection would be 50ms, but through VPN - 250ms.
So, I would prefer to talk to "youtube.com" through my primary connection.

**Comment by clue** [comment]
Hi @ethaniel, I like this idea! :+1:

>  send out pings […]

Sending out pings (ICMP echo requests) requires root privileges, so I'm not sure this is something that many people would like to use :)

Here's my suggested alternative:

> When a new connection is being established, send […] through all available network interfaces (that will be the primary connection + the VPN connection) […] establish the outgoing socket through the faster interface. It adds a little overhead to every new connection, but the resulting speeds can be faster.

In other words: We can concurrently try to open the connection through multiple connectors and just pick the fastest connector. Note that this *will* (wastefully) open quite a few TCP connections that are not needed, but depending on your needs you may or may not notice this.

In the future, we *may* look into adding some kind of smarter heuristic to pick the right connector to begin with, however I'm not sure what we should base this on.

In the meantime and/or as an alternative, you may also (manually) set up separate rules for your common services where you know which connector is the fastest.

**Comment by clue** [comment]
The required connector has been implemented via https://github.com/clue/php-connection-manager-extra/pull/10

This means this could now be relied upon here.

My main issue currently is *how* should the user configure this behavior?

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*
