### ISSUE TITLE
Multiple phpsocks implementation is confusing

### ISSUE THREAD

**Issue by sinasalek** [clue/psocksd#26]
When i found this project, i spend about 20 minutes deciding which repository is what i'm looking for.
They seemed very similar, php-socks-react, php-socks-server, psocksd, php-socks
I think it requires a bit of clarification.

**Comment by clue** [comment]
Thanks for raising this, I think you're absolutely right here :+1: 

> deciding which repository is what i'm looking for

So what were you looking for in the first place? :-)

Perhaps you or anybody else happens to have any ideas on how to improve this?

**Comment by sinasalek** [comment]
I was looking for the server, but i couldn't tell which is which simply by looking at the names :)
I think there should be only one server, php-socks-server and one client php-socks-client. if there is going to be a support for other event loops, it is better to implement it via plugable architecture and in the same repository  (https://github.com/async-interop/event-loop)
In case of psocksd, that can be a different build for releases, not sure why it has its own repo
Also if the other repositories are obsolete, it's better to mention that right at the top with link to the new one.

**Comment by clue** [comment]
Here's the gist of why three independent projects exist:

* If you're looking for an end-user SOCKS server daemon, you may want to use clue/psocksd.
* If you're looking for a SOCKS client implementation, consider using clue/socks-react.
* If you're looking for a SOCKS server implementation, consider using clue/socks-server.

Neither of these projects currently has any overlap, so I think it's actually perfectly fine they're separate. However, I do agree that we *may* have to make these differences more obvious :+1:

**Comment by clue** [comment]
The clue/socks-server package has now been merged into the clue/socks-react package via https://github.com/clue/php-socks-react/pull/52

I'll assume this is resolved and will close this for now, please feel free to report back otherwise :+1:
