### ISSUE TITLE
whitelist IP

### ISSUE THREAD

**Issue by huglester** [clue/psocksd#27]
Hello,

is there any way, so I specify allow only 'source IPs' from specific array, or so? (especially via the CLI)

Thank you

**Comment by clue** [comment]
Thanks for filing this ticket :+1: 

Currently, psocksd only accepts listening on certain IPs (such as your localhost address) or using SOCKS5 authentication to limit which user can use your instance.

This means that psocksd currently does not provide a way to further filter incoming connections. This actually depends on https://github.com/clue/php-socks-server/issues/10 being implemented first.

If anybody feeling like looking into this, PRs would be much appreciated! :+1:

**Comment by clue** [comment]
I still think that this feature makes perfect sense :+1: However, there are currently no immediate plans to build this from my end (no demand at the moment and more important outstanding issues currently), but I would be really happy to accept PRs :+1: 

*(If you need this for a commercial project and you want a quote, please check out my profile and send me an email)*
