### ISSUE TITLE
How do cascading proxies?

### ISSUE THREAD

**Issue by Troodi** [clue/psocksd#29]
I have remote socks5 for example 1.1.1.1:3333, and i want to create socks in my server `php psocksd *:9050` socks my server = 2.2.2.2:9050, but client connecting to 2.2.2.2:9050 but load from other 1.1.1.1:3333 socks. How connect to 2.2.2.2:9050 and display 1.1.1.1 ip? 
For example: client -> my socks -> other socks. How do cascading proxies?

**Comment by clue** [comment]
Thank you for this very valid question!

I agree that the documentation is currently a bit unclear, see also #12.

As an alternative, I would suggest looking into using https://LeProxy.org instead, which aims to be the successor of this project.

I hope this helps :+1:

**Comment by Troodi** [comment]
Thank you so much!
